### ISSUE TITLE
Metrics not being sent to AppOptics

### ISSUE THREAD

**Issue by rlauer-paciolan** [solarwinds/prometheus2appoptics#39]
Hello, I'm running the prometheus2appoptics image in a kubernetes cluster using helm and the following deploy yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus2appoptics
  namespace: prometheus2appoptics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus2appoptics
  template:
    metadata:
      labels:
        app: prometheus2appoptics
    spec:
      containers:
      - name: prometheus2appoptics
        image: solarwinds/prometheus2appoptics
        command: ["./prometheus2appoptics"]
        workingDir: /
        env:
        - name: SEND_STATS
          value: "true"
        - name: APPOPTICS_TOKEN
          value: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus2appoptics
  namespace: prometheus2appoptics
  labels:
    app: prometheus2appoptics
spec:
  selector:
    app: prometheus2appoptics
  ports:
    - name: prometheus2appoptics-port-mapping
      protocol: TCP
      port: 80
      targetPort: 4567
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus2appoptics-ingress
  namespace: prometheus2appoptics
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: prometheus2appoptics.example.com
    http:
      paths:
      - backend:
          serviceName: prometheus2appoptics
          servicePort: 80
```

The service comes up fine:
`[-] Starting on :4567`

When I add the following to our prometheus config:
```
remote_write:

  - url: "http://prometheus2appoptics.example.com/receive"
```
  
  and restart the prometheus pod, I get flooded with this in the logs of the prometheus2appoptics pod:
  
`time="2022-10-14T14:45:38Z" level=info msg="error reading body: http2: response body closed"
time="2022-10-14T14:45:38Z" level=info msg="persisting 1000 Measurements to AppOptics\n"
response status: 202 Accepted
time="2022-10-14T14:45:38Z" level=info msg="error reading body: http2: response body closed"
time="2022-10-14T14:45:39Z" level=info msg="persisting 483 Measurements to AppOptics\n"
response status: 202 Accepted
time="2022-10-14T14:45:39Z" level=info msg="error reading body: http2: response body closed"
time="2022-10-14T14:45:39Z" level=info msg="persisting 1000 Measurements to AppOptics\n"
response status: 202 Accepted
time="2022-10-14T14:45:39Z" level=info msg="error reading body: http2: response body closed"
time="2022-10-14T14:45:40Z" level=info msg="persisting 1000 Measurements to AppOptics\n"
response status: 202 Accepted
time="2022-10-14T14:45:40Z" level=info msg="error reading body: http2: response body closed"
time="2022-10-14T14:45:40Z" level=info msg="persisting 1000 Measurements to AppOptics\n"
time="2022-10-14T14:45:40Z" level=info msg="error reading body: http2: response body closed"
response status: 202 Accepted
time="2022-10-14T14:45:41Z" level=info msg="persisting 484 Measurements to AppOptics\n"
time="2022-10-14T14:45:41Z" level=info msg="error reading body: http2: response body closed"
response status: 202 Accepted
time="2022-10-14T14:45:41Z" level=info msg="persisting 1000 Measurements to AppOptics\n"
response status: 202 Accepted
time="2022-10-14T14:45:41Z" level=info msg="error reading body: http2: response body closed"
time="2022-10-14T14:45:42Z" level=info msg="persisting 1000 Measurements to AppOptics\n"
time="2022-10-14T14:45:42Z" level=info msg="error reading body: http2: response body closed"`

I also don't see any metrics coming in.  Our prometheus pod is using image version prom/prometheus:v2.37.0
